# Generated by Django 6.0 on 2026-04-02 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus_owner', '0012_conductor_conductorduty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductorSeatUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('passenger_name', models.CharField(blank=True, max_length=100)),
                ('passenger_phone', models.CharField(blank=True, max_length=15)),
                ('fare_collected', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('occupied', 'Occupied'), ('cancelled', 'Cancelled'), ('empty', 'Empty')], default='booked', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_seat_updates', to='bus_owner.bus')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_updates', to='bus_owner.conductor')),
                ('from_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_from_updates', to='bus_owner.routestop')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductor_seat_updates', to='bus_owner.busschedule')),
                ('to_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conductor_to_updates', to='bus_owner.routestop')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
