# Generated by Django 5.2.7 on 2025-10-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'RTO Admin'), ('owner', 'Bus Owner'), ('traveller', 'Traveller')], default='traveller', max_length=20),
        ),
    ]
