# Generated by Django 6.0 on 2026-02-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
