# Generated by Django 6.0 on 2026-04-02 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'RTO Admin'), ('owner', 'Bus Owner'), ('traveller', 'Traveller'), ('conductor', 'Bus Conductor')], default='traveller', max_length=20),
        ),
    ]
