# Generated by Django 6.0 on 2026-01-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Checking', 'Checking'), ('Action', 'We will take action'), ('Invalid', 'Invalid complaint')], default='Pending', max_length=20),
        ),
    ]
