# Generated by Django 6.0 on 2026-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_remove_complaint_attachment_complaintattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='complaints/'),
        ),
        migrations.DeleteModel(
            name='ComplaintAttachment',
        ),
    ]
