# Generated by Django 5.2.7 on 2025-11-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0003_alter_booking_options_booking_from_stop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionapplication',
            name='photo',
            field=models.ImageField(null=True, upload_to='concession_photos/'),
        ),
    ]
