# Generated by Django 5.2.7 on 2025-11-10 11:06

import django.db.models.deletion
import django.utils.timezone
import traveller.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0004_concessionapplication_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcessionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=200)),
                ('starting_location', models.CharField(max_length=100)),
                ('ending_location', models.CharField(max_length=100)),
                ('concession_percentage', models.PositiveIntegerField(default=50)),
                ('document', models.FileField(blank=True, null=True, upload_to='concession_docs/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='concession_photos/')),
                ('valid_from', models.DateField(default=django.utils.timezone.now)),
                ('valid_till', models.DateField(default=traveller.models.default_valid_till)),
                ('issued_on', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concession_detail', to='traveller.concessionapplication')),
                ('ecard', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_detail', to='traveller.ecard')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concession_details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Concession Detail',
                'verbose_name_plural': 'Concession Details',
            },
        ),
    ]
