# Generated by Django 5.2.7 on 2025-11-11 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0005_concessiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionapplication',
            name='approved_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
