# Generated by Django 5.2.7 on 2025-11-12 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0006_concessionapplication_approved_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concessiondetail',
            options={},
        ),
        migrations.RemoveField(
            model_name='concessiondetail',
            name='document',
        ),
        migrations.RemoveField(
            model_name='concessiondetail',
            name='photo',
        ),
        migrations.AddField(
            model_name='concessionapplication',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concessionapplication',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concessiondetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ecard',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='concessionapplication',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled'), ('Expired', 'Expired')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='concessiondetail',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='traveller.concessionapplication'),
        ),
        migrations.AlterField(
            model_name='concessiondetail',
            name='ecard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traveller.ecard'),
        ),
        migrations.AlterField(
            model_name='concessiondetail',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ecard',
            name='valid_till',
            field=models.DateField(),
        ),
    ]
