# Generated by Django 5.2.7 on 2025-11-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0007_alter_concessiondetail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='concessionapplication',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
