# Generated by Django 5.2.7 on 2025-11-12 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0008_concessionapplication_rejection_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concessiondetail',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='concessiondetail',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='concessiondetail',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concession_detail', to='traveller.concessionapplication'),
        ),
        migrations.AlterField(
            model_name='concessiondetail',
            name='ecard',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concession_detail', to='traveller.ecard'),
        ),
        migrations.AlterField(
            model_name='concessiondetail',
            name='traveller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concession_details', to=settings.AUTH_USER_MODEL),
        ),
    ]
