# Generated by Django 5.2.7 on 2025-11-17 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0009_concessiondetail_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concessiondetail',
            options={'ordering': ['-issued_on'], 'verbose_name': 'Concession Detail', 'verbose_name_plural': 'Concession Details'},
        ),
    ]
