# Generated by Django 6.0 on 2026-01-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0010_alter_concessiondetail_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
