# Generated by Django 6.0 on 2026-03-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0012_booking_payment_amount_booking_payment_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='journey_duration',
            field=models.DurationField(blank=True, help_text='Duration between selected stops', null=True),
        ),
    ]
