# Generated by Django 6.0 on 2026-03-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0013_booking_journey_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='journey_duration',
        ),
    ]
