# Generated by Django 6.0 on 2026-04-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0014_remove_booking_journey_duration'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
    ]
