# Generated by Django 6.0 on 2026-04-14 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0014_alter_conductorduty_conductor_buslivelocation'),
        ('traveller', '0015_alter_booking_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatAvailabilityCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('available_segments', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_cache', to='bus_owner.busschedule')),
            ],
            options={
                'indexes': [models.Index(fields=['schedule', 'last_updated'], name='traveller_s_schedul_1b5deb_idx')],
                'unique_together': {('schedule', 'seat_number')},
            },
        ),
        migrations.CreateModel(
            name='SeatSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('segment_fare', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='traveller.booking')),
                ('from_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_from', to='bus_owner.routestop')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_segments', to='bus_owner.busschedule')),
                ('to_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_to', to='bus_owner.routestop')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['schedule', 'seat_number', 'from_stop', 'to_stop'], name='traveller_s_schedul_c16d23_idx'), models.Index(fields=['schedule', 'seat_number', 'is_active'], name='traveller_s_schedul_e5916c_idx')],
            },
        ),
    ]
