# Generated by Django 5.2.7 on 2025-10-31 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0002_remove_bus_available_seats_remove_bus_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='available_seats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_owner.route'),
        ),
        migrations.DeleteModel(
            name='BusSchedule',
        ),
    ]
