# Generated by Django 5.2.7 on 2025-10-31 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0004_remove_bus_available_seats_remove_bus_route_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['bus_number'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterField(
            model_name='bus',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='bus_owner.busownerprofile'),
        ),
    ]
