# Generated by Django 5.2.7 on 2025-11-01 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0005_alter_bus_options_alter_bus_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busownerprofile',
            name='company_name',
        ),
    ]
