# Generated by Django 5.2.7 on 2025-11-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0006_remove_busownerprofile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_name',
            field=models.CharField(default='Unnamed Bus', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_contact_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_license',
            field=models.FileField(blank=True, null=True, upload_to='driver_licenses/'),
        ),
        migrations.AddField(
            model_name='bus',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='bus',
            name='insurance_document',
            field=models.FileField(blank=True, null=True, upload_to='insurance_docs/'),
        ),
        migrations.AddField(
            model_name='bus',
            name='owner_contact_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='bus',
            name='pollution_test_certificate',
            field=models.FileField(blank=True, null=True, upload_to='pollution_tests/'),
        ),
        migrations.AddField(
            model_name='bus',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='registration_docs/'),
        ),
    ]
