# Generated by Django 5.2.7 on 2025-11-04 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0007_bus_bus_name_bus_driver_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=100)),
                ('arrival_time', models.TimeField()),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the stop along the route')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='bus_owner.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
