# Generated by Django 5.2.7 on 2025-11-04 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0008_routestop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
