# Generated by Django 5.2.7 on 2025-11-17 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0009_alter_route_distance_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bus_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='bus_owner.bus')),
            ],
        ),
    ]
