# Generated by Django 6.0 on 2026-02-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0010_busphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_path',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routestop',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='routestop',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
