# Generated by Django 6.0 on 2026-04-03 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0012_conductor_conductorduty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductorduty',
            options={'ordering': ['-assigned_at']},
        ),
        migrations.AlterUniqueTogether(
            name='conductorduty',
            unique_together={('conductor', 'bus')},
        ),
        migrations.AlterField(
            model_name='conductorduty',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conductors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conductorduty',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_conductors', to='bus_owner.bus'),
        ),
        migrations.AlterField(
            model_name='conductorduty',
            name='conductor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bus', to='bus_owner.conductor'),
        ),
        migrations.RemoveField(
            model_name='conductorduty',
            name='duty_date',
        ),
        migrations.RemoveField(
            model_name='conductorduty',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='conductorduty',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='conductorduty',
            name='start_time',
        ),
    ]
