# Generated by Django 6.0 on 2026-04-12 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus_owner', '0013_alter_conductorduty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductorduty',
            name='conductor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='duty_assignment', to='bus_owner.conductor'),
        ),
        migrations.CreateModel(
            name='BusLiveLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_locations', to='bus_owner.bus')),
                ('current_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_owner.routestop')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_owner.busschedule')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bus_owner.conductor')),
            ],
        ),
    ]
